In [ ]:
from google.colab import files
uploaded = files.upload()

Saving SIA205.20260226T150209.csv to SIA205.20260226T150209.csv

In [ ]:
import pandas as pd

sia205 = pd.read_csv("SIA205.20260226T150209.csv")

In [ ]:
sia205.head()

,Statistic Label,Year,Deciles,UNIT,VALUE
0,Average equivalised nominal disposable income,2024,1st decile,Euro,14183.0
1,Average equivalised nominal disposable income,2024,2nd decile,Euro,19070.0
2,Average equivalised nominal disposable income,2024,3rd decile,Euro,22231.0
3,Average equivalised nominal disposable income,2024,4th decile,Euro,25338.0
4,Average equivalised nominal disposable income,2024,5th decile,Euro,28377.0

In [ ]:
deciles_2024 = sia205[
    (sia205["Year"] == 2024) &
    (sia205["Statistic Label"] == "Average equivalised nominal disposable income")
].copy()

deciles_2024 = deciles_2024[["Deciles", "VALUE"]]

deciles_2024["Monthly Income"] = deciles_2024["VALUE"] / 12

deciles_2024

       Deciles    VALUE  Monthly Income
0   1st decile  14183.0     1181.916667
1   2nd decile  19070.0     1589.166667
2   3rd decile  22231.0     1852.583333
3   4th decile  25338.0     2111.500000
4   5th decile  28377.0     2364.750000
5   6th decile  31833.0     2652.750000
6   7th decile  35464.0     2955.333333
7   8th decile  40169.0     3347.416667
8   9th decile  46896.0     3908.000000
9  10th decile  78098.0     6508.166667

In [ ]:
deciles_2024["Savings Capacity (15%)"] = deciles_2024["Monthly Income"] * 0.15
deciles_2024

       Deciles    VALUE  Monthly Income  Savings Capacity (15%)
0   1st decile  14183.0     1181.916667                177.2875
1   2nd decile  19070.0     1589.166667                238.3750
2   3rd decile  22231.0     1852.583333                277.8875
3   4th decile  25338.0     2111.500000                316.7250
4   5th decile  28377.0     2364.750000                354.7125
5   6th decile  31833.0     2652.750000                397.9125
6   7th decile  35464.0     2955.333333                443.3000
7   8th decile  40169.0     3347.416667                502.1125
8   9th decile  46896.0     3908.000000                586.2000
9  10th decile  78098.0     6508.166667                976.2250

In [ ]:
pregnancy_cost_model = {
    "Baby Equipment": 2500,
    "Clothing": 500,
    "Supplements": 200,
    "Classes": 200,
    "Travel & Misc": 600
}

total_cost = sum(pregnancy_cost_model.values())
total_cost

4000

In [ ]:
months_remaining = 8
monthly_required = total_cost / months_remaining
monthly_required

500.0

In [ ]:
deciles_2024["Savings Capacity (15%)"]

0    177.2875
1    238.3750
2    277.8875
3    316.7250
4    354.7125
5    397.9125
6    443.3000
7    502.1125
8    586.2000
9    976.2250
Name: Savings Capacity (15%), dtype: float64

In [ ]:
deciles_2024["Can Afford?"] = deciles_2024["Savings Capacity (15%)"] >= monthly_required
deciles_2024

       Deciles    VALUE  Monthly Income  Savings Capacity (15%)  Can Afford?
0   1st decile  14183.0     1181.916667                177.2875        False
1   2nd decile  19070.0     1589.166667                238.3750        False
2   3rd decile  22231.0     1852.583333                277.8875        False
3   4th decile  25338.0     2111.500000                316.7250        False
4   5th decile  28377.0     2364.750000                354.7125        False
5   6th decile  31833.0     2652.750000                397.9125        False
6   7th decile  35464.0     2955.333333                443.3000        False
7   8th decile  40169.0     3347.416667                502.1125         True
8   9th decile  46896.0     3908.000000                586.2000         True
9  10th decile  78098.0     6508.166667                976.2250         True

In [ ]:
deciles_2024["Savings Capacity (20%)"] = deciles_2024["Monthly Income"] * 0.20
deciles_2024["Can Afford at 20%?"] = deciles_2024["Savings Capacity (20%)"] >= monthly_required
deciles_2024

,Deciles,VALUE,Monthly Income,Savings Capacity (15%),Can Afford?,Savings Capacity (20%),Can Afford at 20%?
0,1st decile,14183.0,1181.916667,177.2875,False,236.383333,False
1,2nd decile,19070.0,1589.166667,238.3750,False,317.833333,False
2,3rd decile,22231.0,1852.583333,277.8875,False,370.516667,False
3,4th decile,25338.0,2111.500000,316.7250,False,422.300000,False
4,5th decile,28377.0,2364.750000,354.7125,False,472.950000,False
5,6th decile,31833.0,2652.750000,397.9125,False,530.550000,True
6,7th decile,35464.0,2955.333333,443.3000,False,591.066667,True
7,8th decile,40169.0,3347.416667,502.1125,True,669.483333,True
8,9th decile,46896.0,3908.000000,586.2000,True,781.600000,True
9,10th decile,78098.0,6508.166667,976.2250,True,1301.633333,True

**COST SCENARIOS**

In [ ]:
cost_scenarios = {
    "Essential": 3000,
    "Standard": 4500,
    "Premium": 6500
}

cost_scenarios

{'Essential': 3000, 'Standard': 4500, 'Premium': 6500}

In [ ]:
months_remaining = 8

results = []

for scenario, cost in cost_scenarios.items():
    monthly_required = cost / months_remaining

    for index, row in deciles_2024.iterrows():
        results.append({
            "Scenario": scenario,
            "Decile": row["Deciles"],
            "Monthly Required": monthly_required,
            "Savings Capacity (15%)": row["Savings Capacity (15%)"],
            "Feasible": row["Savings Capacity (15%)"] >= monthly_required
        })

import pandas as pd
results_df = pd.DataFrame(results)

results_df.head(29)

     Scenario       Decile  Monthly Required  Savings Capacity (15%)  Feasible
0   Essential   1st decile             375.0                177.2875     False
1   Essential   2nd decile             375.0                238.3750     False
2   Essential   3rd decile             375.0                277.8875     False
3   Essential   4th decile             375.0                316.7250     False
4   Essential   5th decile             375.0                354.7125     False
5   Essential   6th decile             375.0                397.9125      True
6   Essential   7th decile             375.0                443.3000      True
7   Essential   8th decile             375.0                502.1125      True
8   Essential   9th decile             375.0                586.2000      True
9   Essential  10th decile             375.0                976.2250      True
10   Standard   1st decile             562.5                177.2875     False
11   Standard   2nd decile             562.5                238.3750     False
12   Standard   3rd decile             562.5                277.8875     False
13   Standard   4th decile             562.5                316.7250     False
14   Standard   5th decile             562.5                354.7125     False
15   Standard   6th decile             562.5                397.9125     False
16   Standard   7th decile             562.5                443.3000     False
17   Standard   8th decile             562.5                502.1125     False
18   Standard   9th decile             562.5                586.2000      True
19   Standard  10th decile             562.5                976.2250      True
20    Premium   1st decile             812.5                177.2875     False
21    Premium   2nd decile             812.5                238.3750     False
22    Premium   3rd decile             812.5                277.8875     False
23    Premium   4th decile             812.5                316.7250     False
24    Premium   5th decile             812.5                354.7125     False
25    Premium   6th decile             812.5                397.9125     False
26    Premium   7th decile             812.5                443.3000     False
27    Premium   8th decile             812.5                502.1125     False
28    Premium   9th decile             812.5                586.2000     False